# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink: :slug
# Setup
title:            Library Makers
tagline:          ''
description:      'Recipes, tutorials & resources for current and future library makers. '
site:              http://artefacto.github.io
url:              http://www.librarymakers.net
baseurl:          /

author:
  name:           'Kate Lomax'
  url:            https://twitter.com/katelomax

paginate:         5
paginate_path: "posts/page/:num/"
comments: true

# Custom vars
version:          0.0.5

github:
  repo:           https://github.com/artefacto/librarymakers

gems:
- jekyll-gist
- jekyll-paginate
