### GENERAL SETTINGS ###

# Site settings
title: LibraryMakers
description: "Recipes, tutorials & resources for current and future library makers."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://librarymakers.net"

# Build settings
markdown: kramdown

# Permalinks
permalink: :slug

paginate:         5
paginate_path: "posts/page/:num/"

excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#37bcda" #"#F70031"
  primary_rgb: "55,188,218" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#072730" #"#33004D"
  link: "#32C4EA"
  link_hover: "#A4E1F1"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/artefactors/
  - title: twitter
    url: https://www.twitter.com/artefactors/
  - title: instagram
    url: https://www.instagram.com/artefactors/
  - title: github
    url: https://github.com/artefacto/

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - The Ribbon Factory
    - London
email: hello@artefacto.org.uk

author:
  name:           'Kate Lomax'
  url:            https://twitter.com/katelomax

### GENERAL DATA FOR VARIOUS LOCATIONS ###


# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "We are Artefacto, a creative technology company specialising in learning and making for the libraries, museums, archives and galleries sectors."

# Site ethos or ojective content. Shown on Home and About page.
objective:
    message: "This site was designed to provide a way for library makers to share content, ideas and maker projects in open and collaborative ways."
    actions: <a href="/contribute" class="btn btn-theme">Get involved</a>

gems:
- jekyll-gist
- jekyll-paginate
